.PHONY: run,watch

run:
	processing-java  --sketch=`pwd` --output=`pwd`/output  --force  --run 

watch: 
	watchexec -rce pde "processing-java  --sketch=`pwd` --output=`pwd`/output  --force --run"  	


