package com.zk.entity;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dept.id
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dept.name
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dept.dept
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    private String dept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dept.id
     *
     * @return the value of Dept.id
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dept.id
     *
     * @param id the value for Dept.id
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dept.name
     *
     * @return the value of Dept.name
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dept.name
     *
     * @param name the value for Dept.name
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dept.dept
     *
     * @return the value of Dept.dept
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dept.dept
     *
     * @param dept the value for Dept.dept
     *
     * @mbg.generated Tue Mar 10 13:09:23 CST 2020
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }
}